version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "extra-something-first-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vqpp05m5pcbg"
s3_prefix = "extra-something-first-lambda"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
